version: '3.8'

services:
  synq-app:
    image: ${DOCKERHUB_USERNAME}/synq-app:latest
    container_name: synq-application-container
    ports:
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - /home/ubuntu/keystore.p12:/home/ubuntu/keystore.p12
    restart: unless-stopped